name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 * * *' # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_SHORT_INFO: "TRUE"
          SHOW_LINES_OF_CODE: "TRUE"
          SHOW_TIMEZONE: "False"
          SYMBOL_VERSION: "2"
          SHOW_LOC_CHART: "False"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          #REPOSITORY: <gh_username/gh_username>